# RFSoC ZCU208 / XCZU48DR Complete GPR Hybrid V3
PART ?= xczu48dr-2fsvg1517e
BOARD_PART ?=
PROJECT_NAME ?= gpr_hybrid_v3_zcu208

VIVADO ?= vivado
VITIS_HLS ?= vitis_hls
MATLAB ?= matlab
PYTHON3 ?= python3
JOBS ?= 8

BUILD ?= $(CURDIR)/build
IP_REPO ?= $(BUILD)/ip_repo
RELEASE_DIR ?= $(BUILD)/release

EXPECTED_VIVADO_VERSION ?=
EXPECTED_MATLAB_RELEASE ?= R2024a

# Production MUST start from a verified ZCU208 RFDC + MTS base.
BASE_XPR ?=
BASE_BD ?=
GPR_BD_MAP ?= $(CURDIR)/config/zcu208_gpr_bd_map.tcl
INTEGRATION_MODE ?= mapped
WORK_XPR ?= $(BUILD)/vivado/$(PROJECT_NAME)/$(PROJECT_NAME).xpr

PL_CLOCK_PERIOD_NS ?= 4.069
MAX_TONES ?= 4096
MAX_IFFT ?= 4096
MAX_POSITIONS ?= 512
DEFAULT_N_TONES ?= 256
DEFAULT_N_IFFT ?= 2048
DEFAULT_N_POSITIONS ?= 200
HIL_OUTPUT_DIR ?= $(BUILD)/hil_vectors

export PART BOARD_PART PROJECT_NAME VIVADO VITIS_HLS MATLAB PYTHON3 JOBS
export BUILD IP_REPO RELEASE_DIR EXPECTED_VIVADO_VERSION EXPECTED_MATLAB_RELEASE
export BASE_XPR BASE_BD GPR_BD_MAP INTEGRATION_MODE WORK_XPR
export PL_CLOCK_PERIOD_NS MAX_TONES MAX_IFFT MAX_POSITIONS
export DEFAULT_N_TONES DEFAULT_N_IFFT DEFAULT_N_POSITIONS HIL_OUTPUT_DIR
